trigger:
  - master
  - dev

stages:
- stage: Build
  displayName: Build image - PRD
  jobs:
  - job: Build_PRD
    displayName: Build PRD
    variables:
      - group: GROUP_VARIABLES
    condition: and(contains(variables['Build.SourceBranch'], 'refs/heads/master'), succeeded())
    pool:
      vmImage: $(VM_IMAGE_NAME)
    steps:
    - task: Bash@3
      displayName: Print all variables
      inputs:
        targetType: 'inline'
        script: 'env | sort'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPOSITORY)
        dockerfile: $(DOCKERFILE_PATH)
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(TAG_LATEST)
          $(TAG_ID_PRD)-$(Build.BuildId)
          
  - job: Build_DEV
    condition: and(contains(variables['Build.SourceBranch'], 'refs/heads/dev'), succeeded())
    displayName: Build DEV
    variables:
    - group: GROUP_VARIABLES
    pool:
      vmImage: $(VM_IMAGE_NAME)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPOSITORY)
        Dockerfile: $(DOCKERFILE_PATH)
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(TAG_LATEST)
          $(TAG_ID_DEV)-$(Build.BuildId)