variables:
  KANIKO_CACHE_ARGS: "--cache=true --cache-ttl=96h"
  KANIKO_SNAPSHOT_MODE: "full"

build-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  services:
    - docker:dind
  script:
    - apt install -y curl python3
    - curl https://sdk.cloud.google.com > install.sh
    - ./install.sh --disable-prompts
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - echo "Configuring Google Credentials"
    - echo ${GOOGLE_CREDENTIALS_JSON} > $CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
    - gcloud config set project ${PROJECT_ID}
    - /kaniko/executor
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${ARTIFACT_REGISTRY_HOSTNAME}/${PROJECT_ID}/${GKE_REPOSITORY}/${IMAGE_NAME}:${CI_COMMIT_TAG}"
      --destination "${ARTIFACT_REGISTRY_HOSTNAME}/${PROJECT_ID}/${GKE_REPOSITORY}/${IMAGE_NAME}:${TAG_LATEST}"
      --context "${CI_PROJECT_DIR}"
      --cache=true
      --cache-ttl=96h
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'