FROM node:20.13.0-slim AS builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci --silent
COPY . .

RUN npm run build

FROM node:20.13.0-alpine3.19 AS production

ARG FIREBASE_ADMIN_KEY=${FIREBASE_ADMIN_KEY}

COPY ${FIREBASE_ADMIN_KEY} /usr/src/app/firebase-admin-sdk.json

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/.env.production ./.env.production

CMD [ "npm", "run", "start:prod" ]

FROM node:20.13.0-alpine3.19 AS development

ARG FIREBASE_ADMIN_KEY=${FIREBASE_ADMIN_KEY}

COPY ${FIREBASE_ADMIN_KEY} /usr/src/app/firebase-admin-sdk.json

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/.env.development ./.env.development

CMD [ "npm", "run", "start:dev" ]

FROM node:20.13.0-alpine3.19 AS staging

ARG FIREBASE_ADMIN_KEY=${FIREBASE_ADMIN_KEY}

COPY ${FIREBASE_ADMIN_KEY} /usr/src/app/firebase-admin-sdk.json

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/.env.staging ./.env.staging

CMD [ "npm", "run", "start:staging" ]